### ISSUE TITLE
acceptance test failure in eel-pond/plot-expression.py

### ISSUE THREAD

**Issue by mr-c** [ged-lab/khmer-protocols#129]
``` bash
Writing differentially expressed genes list to 0-vs-6-hour.changed.csv
Got sample spec: 5 from condition 1, 5 from condition 2
Loading differentially expressed gene names from 0-vs-6-hour.changed.csv
Loading gene matrix from 0-vs-6-hour.matrix
plotting...
Output figure to: 0-vs-6-hour.matrix.png
Traceback (most recent call last):
  File "/usr/local/share/eel-pond/plot-expression.py", line 89, in <module>
    main()
  File "/usr/local/share/eel-pond/plot-expression.py", line 86, in main
    savefig(filename)
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 561, in savefig
    return fig.savefig(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1421, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 2220, in print_figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 505, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 451, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1034, in draw
    func(*args)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2086, in draw
    a.draw(renderer)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/lines.py", line 530, in draw
    gc.set_foreground(ln_color_rgba)
  File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 921, in set_foreground
    self._rgb = colors.colorConverter.to_rgba(fg)
  File "/usr/lib/pymodules/python2.7/matplotlib/colors.py", line 365, in to_rgba
    'to_rgba: Invalid rgba arg "%s"\n%s' % (str(arg), exc))
ValueError: to_rgba: Invalid rgba arg "(0.0, 0.0, 1.0, '0.1')"
number in rbga sequence outside 0-1 range
```

``` bash
root@ip-10-180-216-14:/usr/local/share/eel-pond# git status
HEAD detached at protocols-v0.8.3
root@ip-10-180-216-14:~/khmer-protocols# git status
On branch acceptance
Your branch is up-to-date with 'origin/acceptance'.
root@ip-10-180-216-14:/usr/local/share/khmer# git branch -v
* master 792a62a Merge pull request #572 from ged-lab/fix/no-asserts
```

**Comment by mr-c** [comment]
This is still an issue.
